"use strict";

/* TRANSLATIONS */
const translations = {
  en: {
    menu: "MAIN MENU",
    dashboard: "Dashboard",
    grading: "Onion Grading",
    voice: "Ask AgriVoice",
    alerts: "Alerts & Advisory",
    weather: "Weather Center",
    history: "Crop History",
    sensors: "Sensor Dashboard",
    account: "ACCOUNT",
    settings: "Settings",
    online: "AI Online",
    welcome: "Welcome to OnionSort 👋",
    welcomeText: "Your smart companion for onion grading, crop monitoring and farming assistance.",
    overview: "Farm Overview",
    graded: "Onions Graded",
    gradedDesc: "Sample grading records",
    cropHealth: "Crop Health",
    cropHealthDesc: "Sample crop status",
    temperature: "Temperature",
    temperatureDesc: "Demo weather reading",
    quickActions: "Quick Actions",
    gradeOnions: "Grade Onions",
    gradeDesc: "Upload an onion image to view a sample grading result.",
    startGrading: "Start Grading",
    talkAgriVoice: "Talk to AgriVoice",
    talkDesc: "Ask farming questions using your voice.",
    openVoice: "Open AgriVoice",
    liveCamera: "Live Camera",
    cameraDesc: "Open your camera to capture an image.",
    openCamera: "Open Camera",
    onionGrading: "Onion Grading",
    uploadText: "Upload an onion image to view a sample grading report.",
    selectImage: "Select Image",
    analyze: "Analyze Image",
    askAgriVoice: "Ask AgriVoice",
    voiceInstructions: "Speak in your preferred language to ask a farming question.",
    chooseLanguage: "Choose Language",
    tapSpeak: "Tap to Speak",
    voiceOutput: "Your voice input will appear here.",
    speakResponse: "🔊 Speak Response",
    clear: "Clear",
    cameraInstructions: "Start your camera to capture an image of your crop.",
    cameraReady: "Camera is ready",
    startCamera: "Start Camera",
    stopCamera: "Stop Camera",
    capture: "Capture Image",
    alertsAdvisory: "Alerts & Advisory",
    rainAlert: "Rainfall Advisory",
    rainText: "Sample advisory: Monitor field drainage during periods of heavy rainfall.",
    cropAlert: "Crop Monitoring",
    cropText: "Check onion leaves regularly for visible signs of disease or pest activity.",
    waterAlert: "Irrigation Reminder",
    waterText: "Check soil moisture before scheduling irrigation.",
    weatherCenter: "Weather Center",
    humidity: "Humidity",
    rainfall: "Rainfall",
    demoReading: "Demo reading",
    weatherNote: "These values are sample data. Connect a weather API for live information.",
    cropHistory: "Crop History",
    date: "Date",
    crop: "Crop",
    grade: "Grade",
    status: "Status",
    sensorDashboard: "Sensor Dashboard",
    soilTemperature: "Soil Temperature",
    soilMoisture: "Soil Moisture",
    sampleSensor: "Sample sensor reading",
    sensorStatus: "Sensor Status",
    sensorNote: "Connect IoT devices for live readings.",
    profileName: "Profile Name",
    preferredLanguage: "Preferred Language",
    saveSettings: "Save Settings",
    settingsSaved: "Settings saved successfully."
  }
};

/* HINDI */
translations.hi = {
  menu: "मुख्य मेनू",
  dashboard: "डैशबोर्ड",
  grading: "प्याज़ ग्रेडिंग",
  voice: "एग्रीवॉइस से पूछें",
  alerts: "अलर्ट और सलाह",
  weather: "मौसम केंद्र",
  history: "फसल इतिहास",
  sensors: "सेंसर डैशबोर्ड",
  account: "खाता",
  settings: "सेटिंग्स",
  online: "AI ऑनलाइन",
  welcome: "ओनियनसॉर्ट में आपका स्वागत है 👋",
  welcomeText: "प्याज़ ग्रेडिंग, फसल निगरानी और खेती में सहायता के लिए आपका स्मार्ट साथी।",
  overview: "खेत का अवलोकन",
  graded: "ग्रेड किए गए प्याज़",
  gradedDesc: "नमूना ग्रेडिंग रिकॉर्ड",
  cropHealth: "फसल स्वास्थ्य",
  cropHealthDesc: "नमूना फसल स्थिति",
  temperature: "तापमान",
  temperatureDesc: "डेमो मौसम रीडिंग",
  quickActions: "त्वरित कार्य",
  gradeOnions: "प्याज़ ग्रेड करें",
  gradeDesc: "नमूना ग्रेडिंग परिणाम देखने के लिए प्याज़ की तस्वीर अपलोड करें।",
  startGrading: "ग्रेडिंग शुरू करें",
  talkAgriVoice: "एग्रीवॉइस से बात करें",
  talkDesc: "अपनी आवाज़ से खेती के सवाल पूछें।",
  openVoice: "एग्रीवॉइस खोलें",
  liveCamera: "लाइव कैमरा",
  cameraDesc: "तस्वीर लेने के लिए अपना कैमरा खोलें।",
  openCamera: "कैमरा खोलें",
  onionGrading: "प्याज़ ग्रेडिंग",
  uploadText: "नमूना ग्रेडिंग रिपोर्ट देखने के लिए प्याज़ की तस्वीर अपलोड करें।",
  selectImage: "तस्वीर चुनें",
  analyze: "तस्वीर का विश्लेषण करें",
  askAgriVoice: "एग्रीवॉइस से पूछें",
  voiceInstructions: "खेती का सवाल पूछने के लिए अपनी पसंदीदा भाषा में बोलें।",
  chooseLanguage: "भाषा चुनें",
  tapSpeak: "बोलने के लिए टैप करें",
  voiceOutput: "आपका बोला हुआ इनपुट यहाँ दिखाई देगा।",
  speakResponse: "🔊 उत्तर सुनें",
  clear: "साफ़ करें",
  cameraInstructions: "अपनी फसल की तस्वीर लेने के लिए कैमरा शुरू करें।",
  cameraReady: "कैमरा तैयार है",
  startCamera: "कैमरा शुरू करें",
  stopCamera: "कैमरा बंद करें",
  capture: "तस्वीर लें",
  alertsAdvisory: "अलर्ट और सलाह",
  rainAlert: "वर्षा सलाह",
  rainText: "नमूना सलाह: भारी बारिश के दौरान खेत की जल निकासी पर नज़र रखें।",
  cropAlert: "फसल निगरानी",
  cropText: "बीमारी या कीटों के लक्षणों के लिए प्याज़ की पत्तियों की नियमित जाँच करें।",
  waterAlert: "सिंचाई अनुस्मारक",
  waterText: "सिंचाई तय करने से पहले मिट्टी की नमी जाँचें।",
  weatherCenter: "मौसम केंद्र",
  humidity: "आर्द्रता",
  rainfall: "वर्षा",
  demoReading: "डेमो रीडिंग",
  weatherNote: "ये मान नमूना डेटा हैं। लाइव जानकारी के लिए मौसम API जोड़ें।",
  cropHistory: "फसल इतिहास",
  date: "तारीख",
  crop: "फसल",
  grade: "ग्रेड",
  status: "स्थिति",
  sensorDashboard: "सेंसर डैशबोर्ड",
  soilTemperature: "मिट्टी का तापमान",
  soilMoisture: "मिट्टी की नमी",
  sampleSensor: "नमूना सेंसर रीडिंग",
  sensorStatus: "सेंसर स्थिति",
  sensorNote: "लाइव रीडिंग के लिए IoT डिवाइस जोड़ें।",
  profileName: "प्रोफ़ाइल नाम",
  preferredLanguage: "पसंदीदा भाषा",
  saveSettings: "सेटिंग्स सहेजें",
  settingsSaved: "सेटिंग्स सफलतापूर्वक सहेजी गईं।"
};

/* MARATHI */
translations.mr = {
  menu: "मुख्य मेनू",
  dashboard: "डॅशबोर्ड",
  grading: "कांदा ग्रेडिंग",
  voice: "अ‍ॅग्रीव्हॉइसला विचारा",
  alerts: "सूचना आणि सल्ला",
  weather: "हवामान केंद्र",
  history: "पीक इतिहास",
  sensors: "सेन्सर डॅशबोर्ड",
  account: "खाते",
  settings: "सेटिंग्ज",
  online: "AI ऑनलाइन",
  welcome: "ओनियनसॉर्टमध्ये आपले स्वागत आहे 👋",
  welcomeText: "कांदा ग्रेडिंग, पीक निरीक्षण आणि शेतीसाठी मदत करणारा तुमचा स्मार्ट साथीदार.",
  overview: "शेताचा आढावा",
  graded: "ग्रेड केलेले कांदे",
  gradedDesc: "नमुना ग्रेडिंग नोंदी",
  cropHealth: "पिकाचे आरोग्य",
  cropHealthDesc: "नमुना पीक स्थिती",
  temperature: "तापमान",
  temperatureDesc: "डेमो हवामान नोंद",
  quickActions: "जलद क्रिया",
  gradeOnions: "कांदा ग्रेड करा",
  gradeDesc: "नमुना ग्रेडिंग निकाल पाहण्यासाठी कांद्याचा फोटो अपलोड करा.",
  startGrading: "ग्रेडिंग सुरू करा",
  talkAgriVoice: "अ‍ॅग्रीव्हॉइसशी बोला",
  talkDesc: "आपल्या आवाजाने शेतीचे प्रश्न विचारा.",
  openVoice: "अ‍ॅग्रीव्हॉइस उघडा",
  liveCamera: "लाइव्ह कॅमेरा",
  cameraDesc: "फोटो काढण्यासाठी कॅमेरा उघडा.",
  openCamera: "कॅमेरा उघडा",
  onionGrading: "कांदा ग्रेडिंग",
  uploadText: "नमुना ग्रेडिंग अहवाल पाहण्यासाठी कांद्याचा फोटो अपलोड करा.",
  selectImage: "फोटो निवडा",
  analyze: "फोटोचे विश्लेषण करा",
  askAgriVoice: "अ‍ॅग्रीव्हॉइसला विचारा",
  voiceInstructions: "शेतीचा प्रश्न विचारण्यासाठी तुमच्या आवडत्या भाषेत बोला.",
  chooseLanguage: "भाषा निवडा",
  tapSpeak: "बोलण्यासाठी टॅप करा",
  voiceOutput: "तुमचा बोललेला मजकूर येथे दिसेल.",
  speakResponse: "🔊 उत्तर ऐका",
  clear: "पुसून टाका",
  cameraInstructions: "पिकाचा फोटो काढण्यासाठी कॅमेरा सुरू करा.",
  cameraReady: "कॅमेरा तयार आहे",
  startCamera: "कॅमेरा सुरू करा",
  stopCamera: "कॅमेरा बंद करा",
  capture: "फोटो काढा",
  alertsAdvisory: "सूचना आणि सल्ला",
  rainAlert: "पर्जन्य सल्ला",
  rainText: "नमुना सल्ला: जोरदार पावसात शेतातील पाण्याच्या निचऱ्याकडे लक्ष ठेवा.",
  cropAlert: "पीक निरीक्षण",
  cropText: "रोग किंवा किडीच्या लक्षणांसाठी कांद्याची पाने नियमित तपासा.",
  waterAlert: "सिंचन स्मरणपत्र",
  waterText: "सिंचनाचे नियोजन करण्यापूर्वी मातीतील ओलावा तपासा.",
  weatherCenter: "हवामान केंद्र",
  humidity: "आर्द्रता",
  rainfall: "पाऊस",
  demoReading: "डेमो नोंद",
  weatherNote: "ही मूल्ये नमुना डेटा आहेत. थेट माहितीसाठी हवामान API जोडा.",
  cropHistory: "पीक इतिहास",
  date: "तारीख",
  crop: "पीक",
  grade: "ग्रेड",
  status: "स्थिती",
  sensorDashboard: "सेन्सर डॅशबोर्ड",
  soilTemperature: "मातीचे तापमान",
  soilMoisture: "मातीतील ओलावा",
  sampleSensor: "नमुना सेन्सर नोंद",
  sensorStatus: "सेन्सर स्थिती",
  sensorNote: "थेट नोंदींसाठी IoT उपकरणे जोडा.",
  profileName: "प्रोफाइल नाव",
  preferredLanguage: "आवडती भाषा",
  saveSettings: "सेटिंग्ज जतन करा",
  settingsSaved: "सेटिंग्ज यशस्वीरित्या जतन केल्या."
};

/* GUJARATI */
translations.gu = {
  menu: "મુખ્ય મેનૂ",
  dashboard: "ડેશબોર્ડ",
  grading: "ડુંગળી ગ્રેડિંગ",
  voice: "એગ્રીવોઇસને પૂછો",
  alerts: "ચેતવણી અને સલાહ",
  weather: "હવામાન કેન્દ્ર",
  history: "પાક ઇતિહાસ",
  sensors: "સેન્સર ડેશબોર્ડ",
  account: "એકાઉન્ટ",
  settings: "સેટિંગ્સ",
  online: "AI ઓનલાઇન",
  welcome: "ઓનિયનસોર્ટમાં આપનું સ્વાગત છે 👋",
  welcomeText: "ડુંગળી ગ્રેડિંગ, પાક દેખરેખ અને ખેતી સહાય માટે તમારો સ્માર્ટ સાથી.",
  overview: "ખેતરની ઝલક",
  graded: "ગ્રેડ કરેલી ડુંગળી",
  gradedDesc: "નમૂનારૂપ ગ્રેડિંગ રેકોર્ડ",
  cropHealth: "પાકનું સ્વાસ્થ્ય",
  cropHealthDesc: "નમૂનારૂપ પાક સ્થિતિ",
  temperature: "તાપમાન",
  temperatureDesc: "ડેમો હવામાન રીડિંગ",
  quickActions: "ઝડપી ક્રિયાઓ",
  gradeOnions: "ડુંગળી ગ્રેડ કરો",
  gradeDesc: "નમૂનારૂપ ગ્રેડિંગ પરિણામ જોવા માટે ડુંગળીનો ફોટો અપલોડ કરો.",
  startGrading: "ગ્રેડિંગ શરૂ કરો",
  talkAgriVoice: "એગ્રીવોઇસ સાથે વાત કરો",
  talkDesc: "તમારા અવાજથી ખેતીના પ્રશ્નો પૂછો.",
  openVoice: "એગ્રીવોઇસ ખોલો",
  liveCamera: "લાઇવ કેમેરા",
  cameraDesc: "ફોટો લેવા માટે તમારો કેમેરા ખોલો.",
  openCamera: "કેમેરા ખોલો",
  onionGrading: "ડુંગળી ગ્રેડિંગ",
  uploadText: "નમૂનારૂપ ગ્રેડિંગ રિપોર્ટ જોવા માટે ડુંગળીનો ફોટો અપલોડ કરો.",
  selectImage: "ફોટો પસંદ કરો",
  analyze: "ફોટાનું વિશ્લેષણ કરો",
  askAgriVoice: "એગ્રીવોઇસને પૂછો",
  voiceInstructions: "ખેતીનો પ્રશ્ન પૂછવા માટે તમારી પસંદગીની ભાષામાં બોલો.",
  chooseLanguage: "ભાષા પસંદ કરો",
  tapSpeak: "બોલવા માટે ટેપ કરો",
  voiceOutput: "તમારું બોલાયેલું લખાણ અહીં દેખાશે.",
  speakResponse: "🔊 જવાબ સાંભળો",
  clear: "સાફ કરો",
  cameraInstructions: "તમારા પાકનો ફોટો લેવા માટે કેમેરા શરૂ કરો.",
  cameraReady: "કેમેરા તૈયાર છે",
  startCamera: "કેમેરા શરૂ કરો",
  stopCamera: "કેમેરા બંધ કરો",
  capture: "ફોટો લો",
  alertsAdvisory: "ચેતવણી અને સલાહ",
  rainAlert: "વરસાદ સલાહ",
  rainText: "નમૂનારૂપ સલાહ: ભારે વરસાદ દરમિયાન ખેતરના પાણીના નિકાલ પર ધ્યાન રાખો.",
  cropAlert: "પાક દેખરેખ",
  cropText: "રોગ કે જીવાતના ચિહ્નો માટે ડુંગળીના પાંદડાં નિયમિત તપાસો.",
  waterAlert: "સિંચાઈ રિમાઇન્ડર",
  waterText: "સિંચાઈ નક્કી કરતા પહેલાં જમીનનો ભેજ તપાસો.",
  weatherCenter: "હવામાન કેન્દ્ર",
  humidity: "ભેજ",
  rainfall: "વરસાદ",
  demoReading: "ડેમો રીડિંગ",
  weatherNote: "આ મૂલ્યો નમૂનારૂપ ડેટા છે. લાઇવ માહિતી માટે હવામાન API જોડો.",
  cropHistory: "પાક ઇતિહાસ",
  date: "તારીખ",
  crop: "પાક",
  grade: "ગ્રેડ",
  status: "સ્થિતિ",
  sensorDashboard: "સેન્સર ડેશબોર્ડ",
  soilTemperature: "જમીનનું તાપમાન",
  soilMoisture: "જમીનનો ભેજ",
  sampleSensor: "નમૂનારૂપ સેન્સર રીડિંગ",
  sensorStatus: "સેન્સર સ્થિતિ",
  sensorNote: "લાઇવ રીડિંગ માટે IoT ઉપકરણો જોડો.",
  profileName: "પ્રોફાઇલ નામ",
  preferredLanguage: "પસંદગીની ભાષા",
  saveSettings: "સેટિંગ્સ સાચવો",
  settingsSaved: "સેટિંગ્સ સફળતાપૂર્વક સાચવાઈ."
};

/* TAMIL */
translations.ta = {
  menu: "முதன்மை மெனு",
  dashboard: "டாஷ்போர்டு",
  grading: "வெங்காயத் தரப்படுத்தல்",
  voice: "அக்ரிவாய்ஸிடம் கேளுங்கள்",
  alerts: "எச்சரிக்கைகள் & ஆலோசனை",
  weather: "வானிலை மையம்",
  history: "பயிர் வரலாறு",
  sensors: "சென்சார் டாஷ்போர்டு",
  account: "கணக்கு",
  settings: "அமைப்புகள்",
  online: "AI இயங்குகிறது",
  welcome: "ஆனியன்சார்ட்டுக்கு வரவேற்கிறோம் 👋",
  welcomeText: "வெங்காயத் தரப்படுத்தல், பயிர் கண்காணிப்பு மற்றும் விவசாய உதவிக்கான உங்கள் ஸ்மார்ட் துணை.",
  overview: "பண்ணை மேலோட்டம்",
  graded: "தரப்படுத்திய வெங்காயங்கள்",
  gradedDesc: "மாதிரி தரப்படுத்தல் பதிவுகள்",
  cropHealth: "பயிர் ஆரோக்கியம்",
  cropHealthDesc: "மாதிரி பயிர் நிலை",
  temperature: "வெப்பநிலை",
  temperatureDesc: "டெமோ வானிலை அளவீடு",
  quickActions: "விரைவு செயல்கள்",
  gradeOnions: "வெங்காயத்தைத் தரப்படுத்துங்கள்",
  gradeDesc: "மாதிரி தரப்படுத்தல் முடிவைக் காண வெங்காயப் படத்தைப் பதிவேற்றவும்.",
  startGrading: "தரப்படுத்தலைத் தொடங்கு",
  talkAgriVoice: "அக்ரிவாய்ஸுடன் பேசுங்கள்",
  talkDesc: "உங்கள் குரலால் விவசாயக் கேள்விகளைக் கேளுங்கள்.",
  openVoice: "அக்ரிவாய்ஸைத் திற",
  liveCamera: "நேரலை கேமரா",
  cameraDesc: "படம் எடுக்க உங்கள் கேமராவைத் திறக்கவும்.",
  openCamera: "கேமராவைத் திற",
  onionGrading: "வெங்காயத் தரப்படுத்தல்",
  uploadText: "மாதிரி தரப்படுத்தல் அறிக்கையைக் காண வெங்காயப் படத்தைப் பதிவேற்றவும்.",
  selectImage: "படத்தைத் தேர்ந்தெடுக்கவும்",
  analyze: "படத்தை ஆய்வு செய்",
  askAgriVoice: "அக்ரிவாய்ஸிடம் கேளுங்கள்",
  voiceInstructions: "விவசாயக் கேள்வியைக் கேட்க உங்கள் விருப்ப மொழியில் பேசுங்கள்.",
  chooseLanguage: "மொழியைத் தேர்ந்தெடுக்கவும்",
  tapSpeak: "பேச தட்டவும்",
  voiceOutput: "உங்கள் குரல் உள்ளீடு இங்கே தோன்றும்.",
  speakResponse: "🔊 பதிலைக் கேளுங்கள்",
  clear: "அழி",
  cameraInstructions: "உங்கள் பயிரின் படத்தை எடுக்க கேமராவைத் தொடங்குங்கள்.",
  cameraReady: "கேமரா தயார்",
  startCamera: "கேமராவைத் தொடங்கு",
  stopCamera: "கேமராவை நிறுத்து",
  capture: "படம் எடு",
  alertsAdvisory: "எச்சரிக்கைகள் & ஆலோசனை",
  rainAlert: "மழை ஆலோசனை",
  rainText: "மாதிரி ஆலோசனை: கனமழையின் போது வயலின் நீர் வடிகாலைக் கண்காணிக்கவும்.",
  cropAlert: "பயிர் கண்காணிப்பு",
  cropText: "நோய் அல்லது பூச்சி அறிகுறிகளுக்காக வெங்காய இலைகளை அடிக்கடி சரிபார்க்கவும்.",
  waterAlert: "நீர்ப்பாசன நினைவூட்டல்",
  waterText: "நீர்ப்பாசனத்தைத் திட்டமிடும் முன் மண் ஈரப்பதத்தைச் சரிபார்க்கவும்.",
  weatherCenter: "வானிலை மையம்",
  humidity: "ஈரப்பதம்",
  rainfall: "மழைப்பொழிவு",
  demoReading: "டெமோ அளவீடு",
  weatherNote: "இவை மாதிரி தரவுகள். நேரலைத் தகவலுக்கு வானிலை API ஐ இணைக்கவும்.",
  cropHistory: "பயிர் வரலாறு",
  date: "தேதி",
  crop: "பயிர்",
  grade: "தரம்",
  status: "நிலை",
  sensorDashboard: "சென்சார் டாஷ்போர்டு",
  soilTemperature: "மண் வெப்பநிலை",
  soilMoisture: "மண் ஈரப்பதம்",
  sampleSensor: "மாதிரி சென்சார் அளவீடு",
  sensorStatus: "சென்சார் நிலை",
  sensorNote: "நேரலை அளவீடுகளுக்கு IoT சாதனங்களை இணைக்கவும்.",
  profileName: "சுயவிவரப் பெயர்",
  preferredLanguage: "விருப்ப மொழி",
  saveSettings: "அமைப்புகளைச் சேமி",
  settingsSaved: "அமைப்புகள் வெற்றிகரமாகச் சேமிக்கப்பட்டன."
};

/* TELUGU */
translations.te = {
  menu: "ప్రధాన మెనూ",
  dashboard: "డాష్‌బోర్డ్",
  grading: "ఉల్లిపాయ గ్రేడింగ్",
  voice: "అగ్రివాయిస్‌ను అడగండి",
  alerts: "హెచ్చరికలు & సలహా",
  weather: "వాతావరణ కేంద్రం",
  history: "పంట చరిత్ర",
  sensors: "సెన్సార్ డాష్‌బోర్డ్",
  account: "ఖాతా",
  settings: "సెట్టింగ్‌లు",
  online: "AI ఆన్‌లైన్",
  welcome: "ఆనియన్‌సార్ట్‌కు స్వాగతం 👋",
  welcomeText: "ఉల్లిపాయ గ్రేడింగ్, పంట పర్యవేక్షణ మరియు వ్యవసాయ సహాయం కోసం మీ స్మార్ట్ తోడు.",
  overview: "పొలం అవలోకనం",
  graded: "గ్రేడ్ చేసిన ఉల్లిపాయలు",
  gradedDesc: "నమూనా గ్రేడింగ్ రికార్డులు",
  cropHealth: "పంట ఆరోగ్యం",
  cropHealthDesc: "నమూనా పంట స్థితి",
  temperature: "ఉష్ణోగ్రత",
  temperatureDesc: "డెమో వాతావరణ రీడింగ్",
  quickActions: "త్వరిత చర్యలు",
  gradeOnions: "ఉల్లిపాయలను గ్రేడ్ చేయండి",
  gradeDesc: "నమూనా గ్రేడింగ్ ఫలితం చూడటానికి ఉల్లిపాయ చిత్రాన్ని అప్‌లోడ్ చేయండి.",
  startGrading: "గ్రేడింగ్ ప్రారంభించండి",
  talkAgriVoice: "అగ్రివాయిస్‌తో మాట్లాడండి",
  talkDesc: "మీ గొంతుతో వ్యవసాయ ప్రశ్నలు అడగండి.",
  openVoice: "అగ్రివాయిస్ తెరవండి",
  liveCamera: "లైవ్ కెమెరా",
  cameraDesc: "చిత్రం తీయడానికి మీ కెమెరాను తెరవండి.",
  openCamera: "కెమెరా తెరవండి",
  onionGrading: "ఉల్లిపాయ గ్రేడింగ్",
  uploadText: "నమూనా గ్రేడింగ్ నివేదిక చూడటానికి ఉల్లిపాయ చిత్రాన్ని అప్‌లోడ్ చేయండి.",
  selectImage: "చిత్రాన్ని ఎంచుకోండి",
  analyze: "చిత్రాన్ని విశ్లేషించండి",
  askAgriVoice: "అగ్రివాయిస్‌ను అడగండి",
  voiceInstructions: "వ్యవసాయ ప్రశ్న అడగడానికి మీకు నచ్చిన భాషలో మాట్లాడండి.",
  chooseLanguage: "భాషను ఎంచుకోండి",
  tapSpeak: "మాట్లాడటానికి నొక్కండి",
  voiceOutput: "మీ వాయిస్ ఇన్‌పుట్ ఇక్కడ కనిపిస్తుంది.",
  speakResponse: "🔊 సమాధానం వినండి",
  clear: "తొలగించు",
  cameraInstructions: "మీ పంట చిత్రాన్ని తీయడానికి కెమెరాను ప్రారంభించండి.",
  cameraReady: "కెమెరా సిద్ధంగా ఉంది",
  startCamera: "కెమెరా ప్రారంభించండి",
  stopCamera: "కెమెరా ఆపండి",
  capture: "చిత్రం తీయండి",
  alertsAdvisory: "హెచ్చరికలు & సలహా",
  rainAlert: "వర్షపాత సలహా",
  rainText: "నమూనా సలహా: భారీ వర్షాల సమయంలో పొలంలో నీటి పారుదలను గమనించండి.",
  cropAlert: "పంట పర్యవేక్షణ",
  cropText: "తెగులు లేదా చీడపీడల సంకేతాల కోసం ఉల్లి ఆకులను క్రమం తప్పకుండా పరిశీలించండి.",
  waterAlert: "నీటిపారుదల రిమైండర్",
  waterText: "నీటిపారుదల ప్లాన్ చేసే ముందు నేల తేమను తనిఖీ చేయండి.",
  weatherCenter: "వాతావరణ కేంద్రం",
  humidity: "తేమ",
  rainfall: "వర్షపాతం",
  demoReading: "డెమో రీడింగ్",
  weatherNote: "ఈ విలువలు నమూనా డేటా. లైవ్ సమాచారం కోసం వాతావరణ API ని కనెక్ట్ చేయండి.",
  cropHistory: "పంట చరిత్ర",
  date: "తేదీ",
  crop: "పంట",
  grade: "గ్రేడ్",
  status: "స్థితి",
  sensorDashboard: "సెన్సార్ డాష్‌బోర్డ్",
  soilTemperature: "నేల ఉష్ణోగ్రత",
  soilMoisture: "నేల తేమ",
  sampleSensor: "నమూనా సెన్సార్ రీడింగ్",
  sensorStatus: "సెన్సార్ స్థితి",
  sensorNote: "లైవ్ రీడింగ్‌ల కోసం IoT పరికరాలను కనెక్ట్ చేయండి.",
  profileName: "ప్రొఫైల్ పేరు",
  preferredLanguage: "ఇష్టమైన భాష",
  saveSettings: "సెట్టింగ్‌లను సేవ్ చేయండి",
  settingsSaved: "సెట్టింగ్‌లు విజయవంతంగా సేవ్ అయ్యాయి."
};

/* CODE AFTER TRANSLATIONS */
let currentLanguage = "en-IN";
let currentResponse = "";
let cameraStream = null;
let recognition = null;

const languageSelect = document.getElementById("voiceLanguage");
const settingsLanguage = document.getElementById("settingsLanguage");

const languageKey = code => code.split("-")[0];

const t = key =>
  (translations[languageKey(currentLanguage)] || translations.en)[key] ||
  translations.en[key];

function applyLanguage(code) {
  currentLanguage = code;

  const words =
    translations[languageKey(code)] || translations.en;

  document.querySelectorAll("[data-i18n]").forEach(el => {
    const k = el.getAttribute("data-i18n");
    el.textContent =
      words[k] || translations.en[k] || el.textContent;
  });

  if (languageSelect) {
    languageSelect.value = code;
  }

  if (settingsLanguage) {
    settingsLanguage.value = code;
  }

  const activePage = document.querySelector(".page.active");

  const activeNav =
    activePage &&
    document.querySelector(
      `.nav-item[data-page="${activePage.id}"]`
    );

  if (activeNav) {
    const navText = activeNav.querySelector(".nav-text");

    if (navText) {
      document.getElementById("pageTitle").textContent =
        navText.textContent;
    }
  }

  document.documentElement.lang = languageKey(code);
}

if (languageSelect) {
  languageSelect.addEventListener("change", () => {
    applyLanguage(languageSelect.value);
  });
}

if (settingsLanguage) {
  settingsLanguage.addEventListener("change", () => {
    applyLanguage(settingsLanguage.value);
  });
}